### ISSUE TITLE
Can't training RRT_SOP

### ISSUE THREAD

**Issue by Soledad-Z** [uvavision/RerankingTransformer#10]
I'm trying to training on SOP, but I can't run your code. I think in your code `experiment_global.py` line 84 there should be `train_global` rather `evaluate_global`. I simply change it but there will be new issue in next code. I wanna know how to fix it.

**Comment by fwtan** [comment]
May I know the error message you got before you changed L84. (Please always include more specific information like error messages as otherwise we have no clue about the problems you have.)

L84 defines a partial function for evaluation so we should use `evaluate_global`.

**Comment by fwtan** [comment]
Feel free to re-open the issue if you have further questions.
