### ISSUE TITLE
Functions without arguments

### ISSUE THREAD

**Issue by mhmd-mst** [uvavision/RerankingTransformer#12]
Good evening,

I noticed some functions like get_loaders()  was defined with parameters but when callled it doesnt include any due to capture_functions, Where can I find the config file including the parameters default values?

**Comment by fwtan** [comment]
configs for

data: [RRT_GLD/utils/data/dataset_ingredient.py](https://github.com/uvavision/RerankingTransformer/blob/c198e7e351d49a13260392b56df6b171653bb393/RRT_GLD/utils/data/dataset_ingredient.py#L17)

model: [RRT_GLD/models/ingredient.py](https://github.com/uvavision/RerankingTransformer/blob/c198e7e351d49a13260392b56df6b171653bb393/RRT_GLD/models/ingredient.py#L22)
