### ISSUE TITLE
A curious phenomenon in reranking

### ISSUE THREAD

**Issue by aruba01** [uvavision/RerankingTransformer#16]
I do image retrieval task on the code in https://github.com/uvavision/SuperGluePretrainedNetwork. To compare different reranking method, I tried to  replace the Superglue with geometry verification. But the performance is lower than the baseline (do global retrieval only). as far as I am concerned, geometry verification is a commom method to improve the performance.

I wanna know that is this phenomenon normal?  Does it means geometry verification can't improve the performance definitely?

the result of geometry verification is shown below (roxford5k):
> hard
  mAP=45.17
hard_after_gv
  mAP=41.04
medium
  mAP=69.75
medium_after_gv
  mAP=67.29

**Comment by fwtan** [comment]
> I do image retrieval task on the code in https://github.com/uvavision/SuperGluePretrainedNetwork. To compare different reranking method, I tried to replace the Superglue with geometry verification. But the performance is lower than the baseline (do global retrieval only). as far as I am concerned, geometry verification is a commom method to improve the performance.
> 
> I wanna know that is this phenomenon normal? Does it means geometry verification can't improve the performance definitely?
> 
> the result of geometry verification is shown below (roxford5k):
> 
> > hard
> > mAP=45.17
> > hard_after_gv
> > mAP=41.04
> > medium
> > mAP=69.75
> > medium_after_gv
> > mAP=67.29

Unfortunately, I don't think I have a good answer to this question. Diagnosing the performance bottleneck of GV by itself is a research topic. To our knowledge, the performance of GV is highly correlated to the quality of the descriptors (i.e. if there is any domain shift), the overlapping between views, the number of descriptors within the overlapping region, etc.
