### ISSUE TITLE
choice of samplers

### ISSUE THREAD

**Issue by macTracyHuang** [uvavision/RerankingTransformer#17]
Dear author, 

May I know the reason that RandomReplacedIdentitySampler is chosen in global eval and train while Triplet is used in rerank part?
also, where can I find the materials about RandomReplacedIdentitySampler that I can learn the idea behind it?

Thank you so much

**Comment by fwtan** [comment]
> Dear author,
> 
> May I know the reason that RandomReplacedIdentitySampler is chosen in global eval and train while Triplet is used in rerank part? also, where can I find the materials about RandomReplacedIdentitySampler that I can learn the idea behind it?
> 
> Thank you so much

Depending on the loss functions, we used different samplers for global and local matching. Here the global matching involves comparisons between each pair of the samples within a mini-batch (i.e. N x N comparisons), we used  RandomReplacedIdentitySampler to maintain a balanced mini-batch where #samples from the same instance (i.e. views of the same chair) are approximately the same. The local matching involves only triplets and does not rely on the mini-batch statistic so we simply used a TripletSampler.
