### ISSUE TITLE
Question about bounding box handling in Rop experiments

### ISSUE THREAD

**Issue by sungonce** [uvavision/RerankingTransformer#2]
Query Images of the Revisited Oxford/Paris experiment have a bounding box and Oxford/Paris evaluation code **should** not use any part other than this bounding box.
A common solution to this is to crop the input image by the bounding box, to avoid use outer part. (Because the outside of the bounding box gives extra information and this extra information has a huge impact on performance.)
(revisitop: https://github.com/filipradenovic/revisitop/blob/master/python/example_process_images.py, line 49)
(DELG: https://github.com/tensorflow/models/blob/master/research/delf/delf/python/delg/extract_features.py, line 142)

I found that your feature extractor code based on DELG's feature extractor, but the bounding box cropping part is commented out, even when extract oxford/paris dataset.
(https://github.com/uvavision/RerankingTransformer/blob/main/RRT_GLD/delg_scripts/extract_features_gld.py, line 112~118)
(https://github.com/uvavision/RerankingTransformer/blob/882dc70b2550dca32e63d0a2cca219a5953dc7b9/RRT_GLD/delg_scripts/extract_oxford_r50_gldv2.sh)

I've been looking for something that does bounding box cropping, or feature rejection outside the bounding box in other parts of your code, but I couldn't find it.
If your code handles bounding boxes for query images(or features), it would be appreciated if you could tell us which part it is.

**Comment by fwtan** [comment]
[`extract_features_gld.py`](https://github.com/uvavision/RerankingTransformer/blob/main/RRT_GLD/delg_scripts/extract_features_gld.py) is only for extracting the descriptors of the Google Landmarks images for training. 
Google Landmarks v2 has no bounding box annotation so we use the full image for training.

To extract the features of the Revisited Oxford/Paris images for evaluation, please use the [`extract_features.py`](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/delg/extract_features.py) file provided by the DELG repo, which crops the query image using the bounding box annotation.

**Comment by sungonce** [comment]
Thanks for fast reply!
