### ISSUE TITLE
<SEP>?

### ISSUE THREAD

**Issue by ZihaoH** [uvavision/RerankingTransformer#3]
Hello, thanks for bringing the great work.
I wonder that what's the purpose of <SEP> token? I didn't find any explain in your paper. Would you please explain it?

**Comment by fwtan** [comment]
This is a good answer. Unfortunately, I don't have the answer. <SEP> was widely used in the NLP domain, and we chose to follow this convention. Since it is a single token, we didn't run any ablations on it. My best guess is removing <SEP> might not lead to a performance drop.

**Comment by fwtan** [comment]
> Hello, thanks for bringing the great work.
> I wonder that what's the purpose of token? I didn't find any explain in your paper. Would you please explain it?

This is a good answer. Unfortunately, I don't have the answer. was widely used in the NLP domain, and we chose to follow this convention. Since it is a single token, we didn't run any ablations on it. My best guess is removing might not lead to a performance drop.
